#pragma once
/*
#define FRONT_LEFT_SPEED 1
#define FRONT_LEFT_DIREC 2
#define FRONT_LEFT_CANCODER 1
#define FRONT_RIGHT_SPEED 3
#define FRONT_RIGHT_DIREC 4
#define FRONT_RIGHT_CANCODER 2
#define BACK_LEFT_SPEED 5
#define BACK_LEFT_DIREC 6
#define BACK_LEFT_CANCODER 3
#define BACK_RIGHT_SPEED 7
#define BACK_RIGHT_DIREC 8
#define BACK_RIGHT_CANCODER 4*/